nombre: " Informe de error"
descripci贸n: Crea un nuevo ticket para un error.
t铆tulo: " [ERROR] - <t铆tulo>"
etiquetas: [
  "error"
]
cuerpo:
  - tipo: textarea
    id: expected-behaviour
    atributos:
      etiqueta: "Comportamiento esperado"
      descripci贸n: Por favor, ingrese una descripci贸n detallada del comportamiento esperado
      placeholder: Descripci贸n breve y detallada del comportamiento esperado...
    validaciones:
      requerido: true
  - tipo: input
    id: current-behaviour
    atributos:
      etiqueta: "Comportamiento actual"
      descripci贸n: Por favor, ingrese una descripci贸n detallada del comportamiento actual
      placeholder: Descripci贸n breve y detallada del comportamiento actual...
    validaciones:
      requerido: true
  - tipo: textarea
    id: reprod
    atributos:
      etiqueta: "Pasos para reproducir el problema"
      descripci贸n: Por favor, ingrese una descripci贸n expl铆cita de su problema
      value: |
        1. Ir a '...'
        2. Hacer clic en '....'
        3. Desplazarse hasta '....'
        4. Ver error
      renderizado: bash
    validaciones:
      requerido: true
  - tipo: textarea
    id: screenshot
    atributos:
      etiqueta: "Evidencias"
      descripci贸n: Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
      value: |
        ![DESCRIPCIN](ENLACE.png)
      renderizado: bash
    validaciones:
      requerido: false
  - tipo: textarea
    id: logs
    atributos:
      etiqueta: "Registros"
      descripci贸n: Copie y pegue cualquier salida de registro relevante. Esto se formatear谩 autom谩ticamente en c贸digo, por lo que no es necesario utilizar las comillas invertidas.
      renderizado: bash
    validaciones:
      requerido: false
  - tipo: dropdown
    id: browsers
    atributos:
      etiqueta: "Navegadores"
      descripci贸n: 驴En qu茅 navegadores est谩 experimentando el problema?
      m煤ltiple: true
      opciones:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validaciones:
      requerido: false
  - tipo: dropdown
    id: os
    atributos:
      etiqueta: "Sistema operativo"
      descripci贸n: 驴Cu谩l es el sistema operativo afectado?
      m煤ltiple: true
      opciones:
        - Windows
        - Linux
        - Mac
    validaciones:
      requerido: false
